### ISSUE TITLE
Testing creating a Task List

### ISSUE THREAD

**Issue by mjandes-teachable** [mjandes-teachable/markdown-portfolio#2]
This is a test.

**Comment by mjandes-teachable** [comment]
- [ ] Start Phython training on PluralSight
- [ ] ***Review Job Openings - Indeed***
- [ ] Continue GitHub Mark

**Comment by mjandes-teachable** [comment]
- [ ] Start Phython training on PluralSight
- [ ] ***Review Job Openings Indeed***
- [ ] Continue GitHub Mark

**Comment by mjandes-teachable** [comment]
Closing issue
